accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),

]

django_redis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

articles/models.py
from django.db import models
from django.conf import settings 
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Comment(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # article field for 1:N relationship
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        max_length=255,
        label='제목',
        help_text='제목은 255자 이내로 작성하세요', 
        widget=forms.TextInput(
            attrs={
            'class': 'user-input',
            'placeholder': '제목을 입력하세요',
            }
        ),
    )
    content = forms.CharField(
        label='내용',
        help_text='내용을 자유롭게 작성해주세요',
        widget=forms.Textarea(
            attrs={
                'row': 7, 
                'col': 50
            }
        ), 
    )
    
    class Meta:
        model = Article
        # 유저로부터 입력받을 항목은 제목과 내용 두개!
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    title = forms.CharField(
        max_length=255,
        label='댓글 제목', 
        help_text='댓글은 255자 이내로 작성하세요',
        widget=forms.TextInput(
            attrs={
                'class': 'user-comment',
                'placeholder': '댓글을 입력하세요',
            }
        ),
    )

    class Meta:
        model = Comment
        fields = ['title']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as user_login
from django.contrib.auth import logout as user_logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user_login(request, form.get_user())
            return redirect('/')
    else:
        form = AuthenticationForm()
    
    context = { 'form': form }
    return render(request, 'accounts/form.html', context)


def signup(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_login(request, user)
            return redirect('/')
    else:
        form = CustomUserCreationForm()
    
    context = { 'form': form }
    return render(request, 'accounts/form.html', context)


@login_required
def logout(request):    
    user_logout(request)
    return redirect('/')

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm
# Create your views here.
def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = { 'article': article }
    return render(request, 'articles/detail.html', context)


def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('/')
    else:
        form = ArticleForm()
    
    context = { 'form': form }
    return render(request, 'articles/form.html', context)

django_redis/views.py
from django.shortcuts import render
from articles.models import Article
from django.core.cache import cache
import json

DEFAULT_TIMEOUT = 25

def index(request):
    articles = cache.get("articles")
    if not articles:
        articles = Article.objects.order_by('-pk')
        jsonString = json.dumps(articles)
        cache.set("articles", jsonString, timeout=DEFAULT_TIMEOUT)
    else:
        jsonString = cache.get("articles")
        articles = json.loads(jsonString)
    
    context = { 'articles': articles }
    return render(request, 'index.html', context)

accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% block body %}
  {% if request.resolver_match.url_name == 'signup' %}
    <h1>This is signup page</h1>
  {% else %}
    <h1>This is login page</h1>
  {% endif %}

 <form action="" method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="submit">
 </form>

  


{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}
  <h1>This is detail page</h1>

  <section>
    
    <p>title : {{ article.title }}</p>
    <p>content : {{ article.content }}</p>
  </section>
{% endblock body %}

articles/templates/articles/form.html
{% extends 'base.html' %}

{% block body %}
  <h1>write an article</h1>

  <form action="" method="POST">
    {% csrf_token %}

    {{ form }}

    <input type="submit" value="submit">
  </form>

{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}
  <h1>welcome</h1>
  <div>
    <h2>your articles here..</h2>
    {% for article in articles %}
    
    <ul>
      <li>title: {{ article.title }}</li>
      <li>content: {{ article.content }}</li>
      <li>user: {{ article.user }} </li>
      <li>created: {{ article.created_at }}</li>
    </ul>
    {% endfor %}
  </div>

{% endblock body %}

templates/base.html
{% load static %}

<!doctype html>
<html>
  <head>
    <meta chareset="UTF-8">
    <title>Django for Redis</title>
    <!-- link tags will be here -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    {% include 'nav.html' %}

    {% block body %}

    {% endblock body %}
    <!-- script tags will be here  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block body %}
  <h1>welcome to Django-Redis</h1>
  <div>
    <section>
      <h2>wanna write one?</h2>
      <a class="btn btn-primary" href="{% url 'articles:create' %}">Write an article</a>
    </section>
    <h2>your articles here..</h2>
    {% for article in articles %} 
    <ul>
      <li>
        <a href="{% url 'articles:detail' article.pk %}">
          title: {{ article.title }}</li>
        </a>
      <li>content: {{ article.content }}</li>
      <li>user: {{ article.user }} </li>
      <li>created: {{ article.created_at }}</li>
    </ul>
    {% endfor %}
  </div>

{% endblock body %}

templates/nav.html
{% load static %}

<!-- basic navbar component -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        
      </ul>
      {% if request.user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Log Out</a>
      {% else %}
        <a class="btn btn-dark" href="{% url 'accounts:login' %}">Log In</a>
        <a class="btn btn-dark" href="{% url 'accounts:signup' %}">Sign Up</a>
      {% endif %}
    </div>
  </div>
</nav>